id: 99d26c21bb02412c999457579f123c5d
title: Toh_300-The_Sutra_on_Reliance_upon_a_Virtuous_Spiritual_Friend-v1
type: translation
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-04-04T10:04:29.971Z'
  creationid: dirk
  eft-text-id: UT22084-071-014
  eft-text-version: 2.15.3 2020
  xmlns-eft: http://read.84000.co/ns/1.0
